# Generated by Django 5.0.6 on 2024-08-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('contenu', models.CharField(max_length=5000)),
                ('auteur', models.CharField(max_length=200)),
            ],
        ),
    ]
